version: 2
updates:
- package-ecosystem: npm
  directory: "/webapp"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.833.0
    - 2.834.0
    - 2.835.0
    - 2.836.0
    - 2.838.0
    - 2.839.0
    - 2.840.0
    - 2.841.0
    - 2.842.0
    - 2.843.0
    - 2.844.0
    - 2.845.0
    - 2.846.0
    - 2.847.0
    - 2.848.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.852.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.863.0
    - 2.864.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.870.0
    - 2.871.0
    - 2.873.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.878.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.885.0
    - 2.886.0
    - 2.887.0
    - 2.888.0
    - 2.889.0
    - 2.890.0
    - 2.891.0
    - 2.892.0
    - 2.893.0
    - 2.894.0
  - dependency-name: react-query
    versions:
    - 3.13.10
    - 3.13.11
    - 3.13.12
    - 3.13.5
    - 3.13.6
    - 3.13.8
  - dependency-name: react-hook-form
    versions:
    - 7.0.1
    - 7.0.3
    - 7.0.4
    - 7.0.7
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.2
    - 7.2.3
    - 7.3.4
  - dependency-name: date-fns
    versions:
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
    - 2.21.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.4
    - 24.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.21.0
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: react-icons
    versions:
    - 4.1.0
    - 4.2.0
  - dependency-name: react-ga
    versions:
    - 3.3.0
  - dependency-name: eslint-plugin-react-hooks
    versions:
    - 4.2.0
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: lodash
    versions:
    - 4.17.20
